checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: val_total_loss
  verbose: true
  save_top_k: 2
  save_last: true
  auto_insert_metric_name: true
  filename: "metric-{epoch:02d}-{val_total_loss:.4f}"
summary_callback:
  _target_: lightning.pytorch.callbacks.ModelSummary
  max_depth: 8
learningrate:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: val_total_loss
  mode: min
  patience: 20
image1:
  _target_: mt_ssl.callbacks.multitask.CrossReconstruction
  n_images: 30
  normalize: true
image2:
  _target_: mt_ssl.callbacks.multitask.CrossReconstruction
  n_images: 30
  normalize: true
  rec_id: 2
repr:
  _target_: mt_ssl.callbacks.multitask.LatentReprCallback
  n_images: 30
  normalize: true
