s1a_image:
  _target_: mmmv_ssl.callbacks.mae_visu.MAECrossRecClb
  n_images: 10
  opt: s1a
  plot_bands: [0,1,2]
  normalize: false
  value_range: [-0.6,0.5]
s1b_image:
  _target_: mmmv_ssl.callbacks.mae_visu.MAECrossRecClb
  n_images: 10
  opt: s1b
  plot_bands: [0,1,2]
  normalize: false
  value_range: [-0.6,0.5]
s2a_image:
  _target_: mmmv_ssl.callbacks.mae_visu.MAECrossRecClb
  n_images: 10
  normalize: true
  value_range: [100,3000]
  opt: s2a

s2b_image:
  _target_: mmmv_ssl.callbacks.mae_visu.MAECrossRecClb
  n_images: 10
  normalize: true
  value_range: [100,3000]
  opt: s2b
emb_s2a:
    _target_: mmmv_ssl.callbacks.mae_visu.EmbeddingsVisu
    n_images: 10
    opt: s2a
    normalize: false
emb_s1a:
    _target_: mmmv_ssl.callbacks.mae_visu.EmbeddingsVisu
    n_images: 10
    opt: s1a
    normalize: false
learningrate:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor

stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: val/total_loss
  mode: min
  patience: 20

checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: val/total_loss
  verbose: true
  save_top_k: 2
  save_last: true
  dirpath: ${output_dir}/checkpoints/${name}/${run_id}
  auto_insert_metric_name: true
  filename: "{epoch:02d}"
