_target_: mt_ssl.module.multiview_module.MultiViewModule
projector:
  _target_: mt_ssl.model.projector.PerDateProject
  d_in: 400
  l_dim: [64]
  d_out: 64
repr_encoder:
  _target_: mt_ssl.model.lq_repr_encoder.LQReprEncoder
  ubarn:
    _target_: mt_ssl.model.ubarn.UBarn
    ne_layers: 3
    d_model: 64
    d_hidden: 128
    dropout: 0.1
    block_name: pff
    norm_first: false
    nhead: 4
    attn_dropout: 0.1
    encoding_config:
      _target_: mt_ssl.model.utae_unet.Unet
      encoder_widths: [ 64,64,64,128 ]
      decoder_widths: [ 32,32,64,128 ]
      encoder_norm: "group"
      padding_mode: "reflect"
      decoding_norm: "batch"
      return_maps: false
      str_conv_k: 4
      str_conv_s: 2
      str_conv_p: 1
      border_size: 0
      skip_conv_norm: "batch"
    pe_module: null
    max_len_pe: 3000
    pe_cst: 1000
    use_transformer: true
  n_queries: 10
  temp_proj:
    _target_: mt_ssl.model.attention.LearnedQMultiHeadAttention
    n_head: 2
    d_k: 16
    n_q: 10
decoder:
  _target_: mt_ssl.model.decoder.ShallowCADecoder
  d_in: 16
  pe_config:
    _target_: mt_ssl.model.encoding.PositionalEncoder
    T: 1000

final_decoder:
  _target_: mt_ssl.model.convolutionalblock.ConvBlock
  block_name: last
pretrained_load_weights: null
d_repr: 64
reference_time_points: null
load_true_reference_time_points: false
override_pe: false
pretrained_mtan_path: null
mtan_grad: true
pretrained_ubarn_path: null
ubarn_grad: true
temporal_mse: true
