_target_: mmmv_ssl.module.alise_mm.AliseMM
model:
  _target_: mmmv_ssl.model.malice_module.AliseMMModule
  encoder:
    _target_: mmmv_ssl.model.datatypes.EncoderConfig
    encoder_s1:
        _target_: mmmv_ssl.model.datatypes.CleanUBarnConfig
        ne_layers: 3
        d_model: 64
        d_hidden: 128
        dropout: 0.1
        block_name: pff
        norm_first: false
        nhead: 4
        attn_dropout: 0.1
        encoding_config:
          _target_: mmmv_ssl.model.datatypes.UnetConfig
          encoder_widths: [ 64,64,64,128 ]
          decoder_widths: [ 32,32,64,128 ]
          encoder_norm: "group"
          padding_mode: "reflect"
          decoding_norm: "batch"
          return_maps: false
          str_conv_k: 4
          str_conv_s: 2
          str_conv_p: 1
          border_size: 0
          skip_conv_norm: "batch"
    encoder_s2:
        _target_: mmmv_ssl.model.datatypes.CleanUBarnConfig
        ne_layers: 3
        d_model: 64
        d_hidden: 128
        dropout: 0.1
        block_name: pff
        norm_first: false
        nhead: 4
        attn_dropout: 0.1
        encoding_config:
          _target_: mmmv_ssl.model.datatypes.UnetConfig
          encoder_widths: [ 64,64,64,128 ]
          decoder_widths: [ 32,32,64,128 ]
          encoder_norm: "group"
          padding_mode: "reflect"
          decoding_norm: "batch"
          return_maps: false
          str_conv_k: 4
          str_conv_s: 2
          str_conv_p: 1
          border_size: 0
          skip_conv_norm: "batch"
    common_temp_proj:
      _target_: mmmv_ssl.model.datatypes.CommonTempProjConfig
      num_heads: 2
      n_q: 10
    projector:
      _target_: mmmv_ssl.model.datatypes.AliseProjConfig
      l_dim: [ 64 ]
      out_channels: 64
      freeze: true
  decoder:
    _target_: mmmv_ssl.model.datatypes.DecoderConfig
    meta_decoder:
        _target_: mmmv_ssl.model.datatypes.MetaDecoderConfig
        num_heads: 2
        d_k: 64
        intermediate_layers: null
#    pe_config:
#        _target_: mmmv_ssl.model.encoding.PositionalEncoder
    query_s1s2_d: 16
    pe_channels: 64
  input_channels:
    _target_: mmmv_ssl.model.datatypes.DataInputChannels
    s2: 10
    s1: 3
  d_repr: 64

weights:
  w_rec: 1
  w_inv: 1
  w_crossrec: 0.5

batch_size: 1
lr: 0.001
