_target_: mmmmv_ssl.model.utae.UTAE
encoder_widths: [64, 64, 64, 128]
decoder_widths: [32, 32, 64, 128]
out_conv: [32]
str_conv_k: 4
str_conv_s: 2
str_conv_p: 1
agg_mode: att_group
encoder_norm: group
n_head: 16
d_model: 256
d_k: 4
encoder: false
return_maps: false
pad_value: 0
padding_mode: reflect
