datamodule:
  _target_: mt_ssl.data.datamodule.multitask_datamodule.MTDataModule
  num_workers: 4
  max_len: 60
  len_in: 30
  batch_size: 1
  crop_size: 64
  s2_band: null
  path_dir_csv: /home/ad/dumeuri/DeepChange/MMDC_OE/PT_FORMAT_MM3
  modalities: [s2]
  prefetch_factor: 2
  scale_doy: null
  non_blocking: true
