datamodule:
    _target_: mt_ssl.data.datamodule.pastis_datamodule.PASTISDataModule
    crop_size: 64
    s2_band: null
    path_dir_csv: /work/scratch/data/kalinie/results/alise_preentrained
    max_len: 61
    data_dir: /work/CESBIO/projects/DeepChange/Ekaterina/Pastis_OE
    num_workers: 4
