w_rec: 1
w_inv: 1
w_crossrec: 0.5
rec_loss:
  _target_: torch.nn.MSELoss


scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 2
  T_mult: 2


optimizer_monitor: val_total_loss

trainer:
  _target_: lightning.pytorch.Trainer
  log_every_n_steps: 10
  num_nodes: 1
  devices: -1
  val_check_interval: 1.0
  accelerator: gpu
  deterministic: false
  enable_model_summary: false
  max_epochs: 150
  min_epochs: 100
  detect_anomaly: false
  accumulate_grad_batches: 1
  limit_val_batches: 1.0
  limit_train_batches: 1.0
  check_val_every_n_epoch: 1
  profiler: simple
  precision: 32

batch_size: 1
return_attns: true
lr: 0.001
seed: 1

optimizer:
  _target_: torch.optim.Adam
profiler: null
matmul_prec: high

slurm_restart: true
