trainer:
  _target_: lightning.pytorch.Trainer
  log_every_n_steps: 10
  num_nodes: 1
  devices: -1
  val_check_interval: 1.0
  accelerator: gpu
  deterministic: false
  enable_model_summary: false
  max_epochs: 150
  min_epochs: 100
  detect_anomaly: false
  accumulate_grad_batches: 1
  limit_val_batches: 1.0
  limit_train_batches: 1.0
  check_val_every_n_epoch: 1
  profiler: simple
  precision: 32
  num_sanity_val_steps: 0

slurm_restart: true

profiler: null
matmul_prec: high

seed: 1
