return_attns: true
lr: 0.001
seed: 1
batch_size: 2

trainer:
  _target_: lightning.pytorch.Trainer
  log_every_n_steps: 200
  devices: 1
  accelerator: gpu
  deterministic: false
  enable_model_summary: false
  max_epochs: 120
  min_epochs: 100
  detect_anomaly: true
  accumulate_grad_batches: 1
  limit_val_batches: 1.0
  limit_train_batches: 1.0
  check_val_every_n_epoch: 2


loss:
  _target_: torch.nn.CrossEntropyLoss
  reduction: mean
  weight: null
  ignore_index: 0

optimizer:
  _target_: torch.optim.Adam
freeze_representation_encoder: true
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  patience: 10
  factor: 0.05
  min_lr: 0.000001

optimizer_monitor: val/loss
allow_pad: true

metrics:
  accuracy:
    _target_: torchmetrics.classification.MulticlassAccuracy
    average: 'micro'
    ignore_index: 0

require_weights: false
mask_loss: true
calibrate_dataloader: false
profiler: null
matmul_prec: high
slurm_restart: false
