defaults:
  - _self_
  - datamodule: mask_mm_aux.yaml
  - module : alise_mm_proj_aux.yaml
  - train: pretrain_ssl.yaml
  - callbacks: minimal.yaml
  - logger: default.yaml
  - dataset: mask_mm_aux.yaml

original_work_dir: ${hydra:runtime.cwd}
name: "malice_pretrain"

output_dir: /work/scratch/data/${oc.env:USER}/MMDC/results/malice

run_id : ${now:%Y-%m-%d}_${now:%H-%M-%S}

hydra:
  run:
    dir: ${output_dir}/logs/${name}/${run_id}

#data_dir: /work/CESBIO/projects/DeepChange/Iris/MMDC_OE/PT_FORMAT_MM3
data_dir: /work/CESBIO/projects/DeepChange/Ekaterina/MMDC_MALICE


resume_from_checkpoint: null #/work/scratch/data/kalinie/MMDC/results/malice/checkpoints/malice_pretrain/2024-12-09_11-15-33/last.ckpt #null
hydra_config: null
seed: 1
verbose: 0

