defaults:
  - _self_
  - datamodule: mask_mm.yaml
  - module : alise_mm_proj.yaml
  - train: pretrain_ssl.yaml
  - callbacks: minimal.yaml
  - logger: default.yaml
  - dataset: mask_mm.yaml

original_work_dir: ${hydra:runtime.cwd}
name: "malice_pretrain"

output_dir: /work/scratch/data/${oc.env:USER}/MMDC/results/malice

run_id : ${now:%Y-%m-%d}_${now:%H-%M-%S}

hydra:
  run:
    dir: ${output_dir}/logs/${name}/${run_id}
#
#hydra:
#  run:
#    dir: ${path_run_dir}/true_requeue
#  sweep:
#    dir: ${path_export_dir}${hydra.job.name}/requeue
#    subdir: ${hydra.job.override_dirname}
#  job:
#    name: wrec${train.w_rec}_winv${train.w_inv}_wcr${train.w_crossrec}
#path_run_dir: ${path_export_dir}/${hydra.job.name}/wrec${train.w_rec}_winv${train.w_inv}_wcr${train.w_crossrec}/bs${train.batch_size}/proj_freeze${module.projector.freeze}/seed${seed}
load_model: true
resume_from_checkpoint: /work/scratch/data/kalinie/MMDC/results/malice/checkpoints/malice_pretrain/2024-11-13_16-31-04/last.ckpt #null
path_dir_model: null
dir_training: null
seed: 1
#path_export_dir: /home/ad/dumeuri/trainings/mm_mae_trainings
verbose: 0

