train:
  _target_: mmmv_ssl.data.dataset.pretraining_mm_mask.PretrainingMMMaskDataset
  directory: ${data_dir}/train
  crop_type: Center
  s2_tile: [30TXT,31TDL,31TEN,32TPQ,32TPT,32UMB,32UQD,33TVM,33TYJ,33UXR,34UEC]
  modalities: [s2,s1_asc]
  max_len: 60
val:
  _target_: mmmv_ssl.data.dataset.pretraining_mm_mask.PretrainingMMMaskDataset
  directory: ${data_dir}/val
  crop_type: Center
  s2_tile: [30TYR, 31TEK, 32TNR, 32UPC, 33TXK, 34UDB]
  modalities: [s2,s1_asc]
  max_len: 60
test:
  _target_: mmmv_ssl.data.dataset.pretraining_mm_mask.PretrainingMMMaskDataset
  directory : ${data_dir}/val
  crop_type: Center
  s2_tile: [30TYR, 31TEK, 32TNR, 32UPC, 33TXK, 34UDB]
  modalities: [s2,s1_asc]
  max_len: 60
